### ISSUE TITLE
`create_cluster` returning a coroutine not a `ClusterManager`

### ISSUE THREAD

**Issue by alisterburt** [dask-contrib/dask-ctl#30]
Following your example in dask/dask-jobqueue#543 I'm trying to create a cluster using `create_cluster()`

```yaml
version: 1
module: "dask_jobqueue"
class: "SLURMCluster"
args: []
kwargs:
  name: 'dask-worker'
  cores: 112
  memory: '750 GB'
  processes: 14
  queue: 'cpu'
  walltime: '00:30:00'
```

```python
import dask_ctl

cluster = dask_ctl.create_cluster('cluster_spec.yaml')
```

The returned object is a coroutine, not a cluster manager - is this expected? 

I went down the rabbit hole of awaiting it in an async function but wanted to check this was necessary, the docs seem to imply it shouldn't be

Sorry for the barrage of extra work here!
